### ISSUE TITLE
Mail from

### ISSUE THREAD

**Issue by gerardedo** [larrabee/freeipa-password-reset#10]
Currently there is no way to specify "Mail From" using settings.

**Comment by gerardedo** [comment]
Consider:

1. Adding self.smtp_from = options['smtp_from'] and msg['From'] = self.smtp_from at app/providers.py
2. Adding "smtp_from": "from@exameple.com", at PasswordReset/settings.py

**Comment by larrabee** [comment]
Thank you for feedback. Fixed in upstream.
