### ISSUE TITLE
Problems installing on minimal Fedora 29, as well as some other issues  (w/ solutions)

### ISSUE THREAD

**Issue by BioSehnsucht** [larrabee/freeipa-password-reset#12]
This probably just boils down to needing to add further documentation to account for minimal installs, and clarifying some things.

Starting from a minimal Fedora 29 install which then had FreeIPA installed (with all the stuff it needs), I ran into some issues.

1) I needed to install multiple packages that weren't already installed, which can be solved with:
`dnf install gcc git python-ipaclient python-ipalib python-devel python-pip redhat-rpm-config` - this solves multiple issues (lack of `pip`, failure to build during `pip install -r requirements.txt`, not having `git` installed by default, not having python ipaclient or ipalib...)

2) I needed to install `pip install virtualenv` once I had `pip` installed

3) There is no `virtualenv2` ? Using `virtualenv` seemed to work as expected (modifying the relevant step in the README to `virtualenv --system-site-packages ./virtualenv`)

4) It appears I had to login to FreeIPA as `ldap-passwd-reset` and change the password (since it was automatically expired) and re-create the keytab before `kinit` would work from the keytab. I'm not sure if this is normal, or varies by install, or whatever, but at least a mention of it would be useful since I was just getting vague errors on the frontend about "Cannot retrieve kerberos tiket". I only figured it out after looking at what the code was doing to hit that error and then step by step walking through it manually.

5) I got some further errors due to lack of `/home/ldap-passwd-reset` which makes sense as while we added the user from the command line with `ipa` we never created a home directory and it appears the code tries to create some files there. Creating the directory and changed ownership accordingly solved that.

6) I found that while you can set SMTP user/pass to `None` (vs `""`, which would fail due to using empty username/password attempt) to disable attempting user/pass for SMTP auth, this means the From address is invalid and sane SMTP server recipients such as gmail will bounce the message. So probably there should either be a separate way to set the From address that can be set in the provider settings if operating without user/pass is intended to be supported, or just make a note that SMTP user/pass are *required* if using SMTP provider, and instead throw an appropriate exception in the code if they're not set versus attempting to continue without them.

**Comment by larrabee** [comment]
Hello. 
Thank you for feedback.
It all fixed.
