### ISSUE TITLE
Requesting Resources over HTTP instead of HTTPS

### ISSUE THREAD

**Issue by LosaMatova** [larrabee/freeipa-password-reset#13]
Fresh install looks like this: 

![image](https://user-images.githubusercontent.com/46520359/55362338-13856f80-54b0-11e9-9447-30115cc53354.png)

Console displays these errors: 

![Screenshot-20190401185836-1448x134](https://user-images.githubusercontent.com/46520359/55362403-4465a480-54b0-11e9-8912-11457808e6e4.png)

**Comment by larrabee** [comment]
Hello.  
All links in code are relative. It should use HTTPS. I think your problem on client side.  
Can you try to disable all your browser extensions and try to open page in incognito mode?
