### ISSUE TITLE
Mobile instead telephoneNumber

### ISSUE THREAD

**Issue by orynkanov** [larrabee/freeipa-password-reset#19]
Hello!
How to use mobile attribute instead of telephoneNumber?
I tried replacing providers.py in the file, but it does not work.

**Comment by larrabee** [comment]
Привет, да, тебе надо заменить все места с telephoneNumber на mobilephoneNumber (посмотреть как называется поле можно через какой нибудь ldap клиент).

**Comment by orynkanov** [comment]
Эта строка "telephoneNumber" находится только в файле providers.py.
Я её заменил на mobile (посмотрел в LDAP).
Но при шаге 2 - ошибка. Хотя точно у пользователя есть правильный номер телефона.
![ipa-mobile](https://user-images.githubusercontent.com/19415018/62536597-2a7a0b00-b870-11e9-8efb-837837b5b668.png)

**Comment by larrabee** [comment]
Попробуй в send_token добавить print(user['result']), что бы посмотреть, что в объекте юзер. Похоже у пользователя ldap-password-reset нет права читать это поле.

**Comment by orynkanov** [comment]
Мы разобрались  в чем было дело:
в pwdmanager.py в "def __get_user(self, uid):" запрашивается информация о пользователе так -user = api.Command.user_show(uid=unicode(uid)).
При этом отображается только атрибут (телефонный) - telephoneNumber.
Если запрашивать так - user = api.Command.user_show(uid=unicode(uid), all=True), то mobile тоже показывается и другие не пустые атрибуты тоже.

**Comment by larrabee** [comment]
Спасибо за развернутый ответ, я добавил функционал по смены имени атрибута в мастер.
