### ISSUE TITLE
Error Message "Cannot retrieve Kerberos ticket"

### ISSUE THREAD

**Issue by kbetsis** [larrabee/freeipa-password-reset#24]
Hi 

I've followed the exact same guidelines as to enable the reset page however, i am getting an error on every attempt for all users as shown below.

![image](https://user-images.githubusercontent.com/14052268/68797974-3ab73880-065e-11ea-8b4e-018dfab4a724.png)

Is there a way i can resolve this?

**Comment by larrabee** [comment]
Hello.
Check that keytab file exists and have right permissions (by default it should have path `/opt/data/IPAPasswordReset/ldap-passwd-reset.keytab`.)

**Comment by kbetsis** [comment]
Hi 

I have it in the default path and it is populated
Kindly see below:
`drwxr-xr-x. 3 ldap-passwd-reset ldap-passwd-reset    30 Nov 13 19:01 ..
-rw-r--r--. 1 ldap-passwd-reset ldap-passwd-reset    88 Nov 13 19:01 .gitignore
-rw-r--r--. 1 ldap-passwd-reset ldap-passwd-reset 35141 Nov 13 19:01 LICENSE
-rw-r--r--. 1 ldap-passwd-reset ldap-passwd-reset   304 Nov 13 19:01 requirements.txt
-rw-r--r--. 1 ldap-passwd-reset ldap-passwd-reset  4308 Nov 13 19:01 README.md
drwxr-xr-x. 4 ldap-passwd-reset ldap-passwd-reset    73 Nov 13 19:01 PasswordReset
drwxr-xr-x. 2 ldap-passwd-reset ldap-passwd-reset   103 Nov 13 19:01 service
drwxr-xr-x. 8 ldap-passwd-reset ldap-passwd-reset   163 Nov 13 19:01 .git
drwxr-xr-x. 5 ldap-passwd-reset ldap-passwd-reset    82 Nov 13 19:01 virtualenv
drwxr-xr-x. 6 ldap-passwd-reset ldap-passwd-reset   178 Nov 13 19:34 .
-rw-------. 1 root              root                184 Nov 13 19:34 ldap-passwd-reset.keytab`

**Comment by kbetsis** [comment]
False alarm i changed the owner to ldap-passwd-reset and it's OK now.

Sorry for the trouble and thanks for the help

**Comment by tceydeliler** [comment]
Hi,
I have same error.
I have keytab files and owner is ldap-passwd-reset. What should I do?

> [root@pnbipa ~]# cd /opt/data/IPAPasswordReset/
[root@pnbipa IPAPasswordReset]# ls -la
total 56
drwxr-xr-x 6 ldap-passwd-reset ldap-passwd-reset   178 May 29  2024 .
drwxr-xr-x 3 root              root                 30 May 29  2024 ..
drwxr-xr-x 8 ldap-passwd-reset ldap-passwd-reset   163 May 29  2024 .git
-rw-r--r-- 1 ldap-passwd-reset ldap-passwd-reset    88 May 29  2024 .gitignore
-rw------- 1 ldap-passwd-reset ldap-passwd-reset   310 May 29  2024 ldap-passwd-reset.keytab
-rw-r--r-- 1 ldap-passwd-reset ldap-passwd-reset 35141 May 29  2024 LICENSE
drwxr-xr-x 4 ldap-passwd-reset ldap-passwd-reset    73 May 29  2024 PasswordReset
-rw-r--r-- 1 ldap-passwd-reset ldap-passwd-reset  4772 May 29  2024 README.md
-rw-r--r-- 1 ldap-passwd-reset ldap-passwd-reset   304 May 29  2024 requirements.txt
drwxr-xr-x 2 ldap-passwd-reset ldap-passwd-reset   103 May 29  2024 service
drwxr-xr-x 5 ldap-passwd-reset ldap-passwd-reset    77 May 29  2024 virtualenv
