### ISSUE TITLE
Password reset with account unlock feature?

### ISSUE THREAD

**Issue by zerov3** [larrabee/freeipa-password-reset#26]
Hi, firstly i would like to say thank you so much for this self-service password reset portal! It worked like a charm and simple to understand!

However i noticed that the self-service password reset does not come with account unlock, which causes confusion towards end user who did password reset but were not able to access to servers due to account being locked ( Multiple attempt to login prior to account reset ). By any chance we will be looking at this feature near future?

I'm not sure whether this is the right place to post, but do delete this thread if i'm wrong.

**Comment by larrabee** [comment]
Hello.  
it's easy to add this feature. Added to master.

**Comment by zerov3** [comment]
Thanks! The unlock feature works! However, i noticed that there is 1 wrong error message shown.

When a user account is not lock and trigger the password reset, error message thrown "Cannot update your password. no modifications to be performed" , but backend wise the account's password did changed.

**Comment by larrabee** [comment]
Hello. Thanks for testing. Fixed.

**Comment by zerov3** [comment]
Hi, sorry to bother you again, receiving new error.
Tried using this password> asdf@1234

Cannot update your password. int() argument must be a string or a number, not 'tuple'

**Comment by larrabee** [comment]
Fixed;)

**Comment by zerov3** [comment]
Thanks! It's working great now!
