### ISSUE TITLE
.keytab is not executing 

### ISSUE THREAD

**Issue by fsadoon** [larrabee/freeipa-password-reset#30]
hi again, the ldap-passwd-reset.keytab isn't renewing the tickets manually, 

i believe some cron job is calling it to renew tickets but i can not find that job  shall i create something like : 

`* */2 * * * /usr/bin/kinit ldap-passwd-reset@ipa.local -k -t /opt/data/IPAPasswordReset/ldap-passwd-reset.keytab`
?

**Comment by fsadoon** [comment]
one more thing ! what do you mean by CSRF key? is it my SSH Key ?

**Comment by larrabee** [comment]
Hello.
1. Keytab file renewed on request. You can find renew code here: [pwdmanager.py#L53](https://github.com/larrabee/freeipa-password-reset/blob/master/PasswordReset/app/pwdmanager.py#L53)
2. No, CSRF key is random string. You should genare it by openssl `openssl rand -base64 64` or use another tool or write a lot of random symbols.

**Comment by fsadoon** [comment]
thanks a lot ! then no harm of having a cron script runs that every 1 day
