### ISSUE TITLE
Block password reset for admin user

### ISSUE THREAD

**Issue by AltiUP** [larrabee/freeipa-password-reset#37]
Is it possible to block the password reset for the admin user?

Chris.

**Comment by larrabee** [comment]
Hello.
By default the app cannot update password of admin users (members of group "admins").  


Default RBAC permission "System: Change User password" have filter "(!(memberOf=cn=admins,cn=groups,cn=accounts,dc=ultimate-guitar,dc=com))"

**Comment by AltiUP** [comment]
Hi,

Thank you! I didn't pay attention to that rule.

Chris
