### ISSUE TITLE
Phone number in wrong format

### ISSUE THREAD

**Issue by rajneshsiwal** [larrabee/freeipa-password-reset#4]
Thanks for the password reset application.
It really looks cool.
But, I am not able to reset the password.
The message I see it "Phone number in wrong format" when I click on reset.
Phone Number I am using +918447740700

**Comment by larrabee** [comment]
Hello. Thanks for reporting. This bug is fixed now.

**Comment by larrabee** [comment]
Bug fixed, closed.
