### ISSUE TITLE
how to change from listening on 127.0.0.1:8000

### ISSUE THREAD

**Issue by lorenzohuerta** [larrabee/freeipa-password-reset#42]
i am trying to debug some remote connectivity that i believe is breaking because the tool is trying to connect to 127.0.0.1:8000  , is it possible to change this config?

**Comment by larrabee** [comment]
Hello.
If you want to run server listen on all interfaces you should change systemd unit (file `service/ldap-passwd-reset.service`) from
```
ExecStart=/opt/data/IPAPasswordReset/virtualenv/bin/python /opt/data/IPAPasswordReset/PasswordReset/manage.py runserver
```
to
```
ExecStart=/opt/data/IPAPasswordReset/virtualenv/bin/python /opt/data/IPAPasswordReset/PasswordReset/manage.py runserver 0.0.0.0:8000
```

**Comment by lorenzohuerta** [comment]
cool thanks!
