### ISSUE TITLE
SMS with tokens

### ISSUE THREAD

**Issue by agconstantin** [larrabee/freeipa-password-reset#6]
Can it work without this feature? Or is it a way to replace it with an email instead of SMS?
Thanks.

**Comment by agmtr** [comment]
> Can it work without this feature? Or is it a way to replace it with an email instead of SMS?
> Thanks.

https://github.com/agmtr/freeipa-password-reset

**Comment by larrabee** [comment]
Hello. Yep, its possible. I will add this feature in 5-7 days.

**Comment by larrabee** [comment]
Hello again;) 
Email feature was added to upstream.

**Comment by agconstantin** [comment]
Great, will test this out and let you know if any issues arise.
