### ISSUE TITLE
requirements.txt lists unavailable version of django

### ISSUE THREAD

**Issue by anthonyclarka2** [larrabee/freeipa-password-reset#7]
The requirements.txt file lists "django==1.11.19" as a dependency, but that version is not available.

Editing the requirements.txt file and increasing the version of django to 1.11.20 allows "pip install -r requirements.txt" to succeed.

**Comment by larrabee** [comment]
Hello. 
Thank you for report. Fixed now.

**Comment by anthonyclarka2** [comment]
Thank you!
