### ISSUE TITLE
Clarification needed on two items

### ISSUE THREAD

**Issue by anthonyclarka2** [larrabee/freeipa-password-reset#8]
Hello, I had 2 questions and was hoping you could answer them?

1) When the password reset page is submitted, I get a message like this: "Cannot update your password. Insufficient access: Insufficient 'write' privilege to the 'krbPasswordExpiration' attribute of entry 'uid=test,cn=users,cn=accounts,dc=dev,dc=example,dc=net'." On line 62 of pwdmanager.py you are using the api.Command.user_mod to set the password, do we need to also set the krbPasswordExpiration attribute or should the FreeIPA system do that for us? Can I just comment out that line?

2) Despite the message above, the reset process does work and sets the password. When testing the new login on the ipaserver/ipa/ui/ url, I'm told that the password needs to be changed. This is the same behaviour as when an admin resets the user's password. Is that correct?

Thank you very much!

**Comment by larrabee** [comment]
Hello.
1. 
* Check that you grant "Modify Users and Reset passwords" privilege to role "Self Password Reset" (you can grant it with command `ipa role-add-privilege "Self Password Reset" --privileges="Modify Users and Reset passwords"`).  
* Check that `Modify Users and Reset passwords` privilege have permission to `System: Change User password`.  (You can found it in RBAC->Privileges)
* Check that `System: Change User password` permission have write permission to field `krbpasswordexpiration`. (You can found it in RBAC->Permissions).
* Try to reset password. It should change successfully.

2. This issue related to your first problem. Fix first issue and this problem gone away;)

**Comment by anthonyclarka2** [comment]
Our instance of FreeIPA didn't have "krbpasswordexpiration" checked in the permission "System: Change User Password". I enabled that and tested again, but still got the same message as before. Do I need to re-create the keytab for ldap-passwd-reset user?

**Comment by larrabee** [comment]
Try to restart app (`systemctl restart ldap-passwd-reset.service`) and try again.

**Comment by anthonyclarka2** [comment]
On your advice, I tried stopping and starting the service again, but got the same warning/error as before. I'll dig into my logs to see if I can find what the issue is.

My IPA version is 4.4.0-14.el7.centos.7 and comes from the CentOS 7 yum repo. I've been unable to update because our current password reset site uses an overly-complex proxy and different hostname, so I've been trying to get this to work so I can update. Don't worry about diagnosing this too much, I'll see what I can discover.

Thank you very, very much for your speedy replies. I'm really impressed! 🥇

**Comment by larrabee** [comment]
You can try it with admin keytab and check that its work. 
Additionally you can check that write permission to `krbpasswordexpiration` is saved.
Thank you;)

**Comment by anthonyclarka2** [comment]
It's definitely an issue with our local FreeIPA instance. I checked a new test install of FreeIPA and the krbpasswordexpiration attribute is correctly a part of "system: change user password". So there's something wrong with our FreeIPA. I will let you know if I have any other questions, thank you for your help so far.
