### ISSUE TITLE
Support for REDIS AUTH

### ISSUE THREAD

**Issue by gerardedo** [larrabee/freeipa-password-reset#9]
Currently there is no support for Redis Auth with Password

**Comment by gerardedo** [comment]
Consider:

1. Adding REDIS_PASSWORD at PasswordReset/PasswordReset/settings.py
2. Modify PasswordReset/app/pwdmanager.py to self.redis = redis.StrictRedis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB, password=settings.REDIS_PASSWORD)

**Comment by larrabee** [comment]
Thank you for feedback. Fixed in upstream.
